### ISSUE TITLE
Too Much Text Printed with CMake 3.17.0

### ISSUE THREAD

**Issue by qak** [openmeeg/findmkl_cmake#21]
FindMKL uses the variable [CMAKE_FIND_DEBUG_MODE](https://github.com/openmeeg/findmkl_cmake/blob/25535429fea3ad80e2ca1306a98ccb14781964ae/cmake/FindMKL.cmake#L80) to control whether several [debug messages](https://github.com/openmeeg/findmkl_cmake/blob/25535429fea3ad80e2ca1306a98ccb14781964ae/cmake/FindMKL.cmake#L284) are printed. Starting from version 3.17.0, this variable [is also used](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_DEBUG_MODE.html) by CMake for a similar purpose. Because FindMKL sets this variable by default, using the package prints a huge amount of output. Otherwise FindMKL works without problems. I think the correct thing to do would be for FindMKL to simply use a different variable for controlling whether its debug messages are printed.

**Comment by agramfort** [comment]
Pull request very welcome. Thanks a lot

>
