### ISSUE TITLE
MacOs; MKL version 2020.1; Move of mkl_linker_tool

### ISSUE THREAD

**Issue by PelleReyniers** [openmeeg/findmkl_cmake#23]
In the MKL library version 2020.1, Platform MacOs, the path of the linker tool has moved.
Previously this was ${MKL_ROOT_DIR}/tools/mkl_link_tool, now this is ${MKL_ROOT_DIR}/bin/mkl_link_tool/mkl_link_tool. 

After adjusting, the script works as stated.

**Comment by agramfort** [comment]
thanks

can you send us a PR?

>

**Comment by qak** [comment]
This has been fixed in commit 7c3b602.
